name: Trigger API to recalculate leaderboard data

on:
  schedule:
    # Runs "at minute 0 past every hour" (see https://crontab.guru)
    - cron: "0 * * * *"
jobs:
  build:
    name: Recalculate leaderboard Data
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://burnlog.vercel.app/api/leaderboard-job
      - name: cURL request
        run: curl -X POST -d {} https://burnlog.vercel.app/api/leaderboard-job-treats
