# .github/workflows/scheduled-builds.yml
name: Trigger API to recalculate shame data

on:
  schedule:
    # Runs "at minute 0 past every hour" (see https://crontab.guru)
    - cron: "0 * * * *"
jobs:
  build:
    name: Recalculate Flame Shame Data
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X POST -d {} https://burnlog.vercel.app/api/shame-data-job
